-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 19:30:39 2019
-- Model: New Model    Version: 1.0
-- Author: Jamil Gomes 



create database lp3;
use lp3;

CREATE TABLE IF NOT EXISTS curso (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`)
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS aluno (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `rg` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(50) NULL,
  PRIMARY KEY (`codigo`)
 )ENGINE = InnoDB;
 
 CREATE TABLE IF NOT EXISTS matricula (
 codAluno int not null,
 codCurso int not null,
 primary key(codAluno, codCurso),
 CONSTRAINT `fk_matricula_curso`
    FOREIGN KEY (`codCurso`) REFERENCES curso (codigo) ON DELETE CASCADE,
 CONSTRAINT `fk_matricula_aluno`
    FOREIGN KEY (`codAluno`) REFERENCES aluno (codigo) ON DELETE CASCADE
 );
 
 
  CREATE TABLE IF NOT EXISTS professor (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`)
 )ENGINE = InnoDB;
 
 CREATE TABLE IF NOT EXISTS disciplina (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `ementa` TEXT NOT NULL,
  `ch` VARCHAR(45) NOT NULL,
  `codProf` INT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_disciplina_professor`
    FOREIGN KEY (`codProf`) REFERENCES professor (codigo) ON DELETE CASCADE
  )ENGINE = InnoDB;
  
 
 CREATE TABLE IF NOT EXISTS grade (
	 ano varchar(4),
	 codDisc int not null,
	 codCurso int not null,
	 primary key(codDisc, codCurso),
	 CONSTRAINT `fk_grade_curso`
		FOREIGN KEY (`codCurso`) REFERENCES curso (codigo) ON DELETE CASCADE,
	 CONSTRAINT `fk_grade_disciplina`
		FOREIGN KEY (`codDisc`) REFERENCES disciplina (codigo) ON DELETE CASCADE
 )ENGINE = InnoDB;
 
 
 insert into curso (codigo, nome) values (1,"Sistemas de Informação"), (2,"Filosofia"), (3,"Geografia"), (4,"Psicologia"), (5,"Letras");
 insert into professor(codigo, nome) values (1,"Yusuke Urameshi"),(2,"Saitama Sensei"),(3,"All Mighty"),(4,"Kakashi"),(5,"Tsunade");
 insert into disciplina(codigo,nome,ementa,ch) values (1,"Calculo 1","blablabla","90"),(2,"Filosofia Moderna","blablabla","60"),(3,"Linguagem de Programação 3","blablabla","90");
 insert into aluno (codigo, nome, endereco, rg, cpf, telefone) values (1,"Naruto Uzumaki","vila da folha","28007472004-6","022.333.444-20","(98)2222-3333"), (2,"Sasuke Uchiha","vila da folha","28007473304-6","222.333.444-20","(98)2222-3232");
 
 
select * from disciplina;

select * from professor;

select * from matricula;
select disciplina.nome, disciplina.ch from disciplina inner join grade on disciplina.codigo = grade.codDisc inner join curso on curso.codigo = grade.codCurso where curso.nome = "Sistemas de Informação";
 
 